### PR TITLE
updated last-used date when a searched cipher is clicked

### LINKED ISSUE #1391: Double-clicking login autofills the incorrect credentials
## Describe the Bug

If autofill is enabled, double-clicking a login from the extension often fills credentials from **a different** login which matches the site URL.

When using the search box to find and launch a login URL, it can reasonably be expected that whichever specific login a user double-clicks is the particular set of credentials that the user wants to use in that instance. Autofilling credentials from a DIFFERENT login than the one clicked is, IMHO, not only a bug, but a security risk, since the user may unknowingly log in to a site using the wrong set of credentials and then proceed to use the site under the wrong persona.

## Steps To Reproduce

This bug manifests if the user has multiple logins for the same target website. To see the problem:

1. Use the extension drop-down window to search for a site at which you have multiple logins (eg. usernameA, usernameB, usernameC).
2. Double-click on the login for "usernameA" to launch the site.

## Expected Result

The credentials for "usernameA" should be autofilled, since that is the specific login that was double-clicked.

## Actual Result

The credentials for "usernameA", "usernameB" or "usernameC" may be autofilled, based on whichever login was most recently used.

## Environment

- Operating system: Windows 10
- Browser: Chrome 83.0.4103.116 (Official Build) (64-bit)
- Build Version (go to "Settings" → "About" in the app): 1.46.1

### PR DESCRIPTION
**Pull request by addisonbeck**
Resolves #1391 

### Issue
When using the search bar to launch a url & autofill the autofill process is not using the login that was clicked, it is using the last used login previous to the clicked login. 

### Resolution
We can locally track last launched logins and get that data back for autofill

jslib will need to be updated to a pending commit before the build here will work

### CODE REVIEW

**Comment by kspearrin** [comment]
I don't think this is the right solution. Last used date is used to detect the last time this item was autofilled. That may or may not be the case when launching an item from the listing like this. I feel like we need to keep track of the last launched date or something and use that to autofill if it was within the last 30 seconds or something

**Comment by addisonbeck** [comment]
@kspearrin How's this? [See jslib PR also.](https://github.com/bitwarden/jslib/pull/174)

**Comment by kspearrin** [comment]
Can't you also launch from the "View" page?

**Comment by xusoo** [comment]
Another idea that comes to mind: I see that `chrome.tabs.create()` allows a callback. We could get the tab id from there and maintain a "launch cache" with a small TTL. Then on page load, look up that cache and check if there is any login associated to the current tab id.

```js
    static createNewTab(url: string, extensionPage: boolean = false) {
        if (BrowserApi.isChromeApi) {
            chrome.tabs.create({ url: url }, (tab) => {
                // We can get the tabId from this callback (although the callback should be passed from the caller)
            });
        } else if (BrowserApi.isSafariApi) {
            SafariApp.sendMessageToApp('createNewTab', url, true);
        }
    }
```

The only problem is that I don't know if Safari allows to do something similar? @kspearrin

**Comment by addisonbeck** [comment]
> Can't you also launch from the "View" page?

Yes, I see that, but that launch logic lives in jslib. I'll need to follow up with another PR there to track when a launch happens.

**Comment by kspearrin** [comment]
Seems fine. Let's wait til next week after we cut the release.

**Pull request closed without merging**
