### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by vins345**
Add    "selectFolder" translate:
"selectFolder": {
    "message": "Wybierz folder..."

### CODE REVIEW

**Comment by tgreer-bw** [comment]
Hi @vins345! We leverage [Crowdin](https://crowdin.com/translate/bitwarden-browser) to handle translations. It looks like this string may not have made it into the main localization file, but once it has, you'll be able to translate there to sync back into the extension :+1:

@cscharf perhaps it needs synced?

**Comment by cscharf** [comment]
Hi @vins345 , you should be able to translate this in Crowdin. We generally sync translations back into our repo from Crowdin when we cut release candidate branches as part of our regression testing.

**Comment by vins345** [comment]
> Hi @vins345 , you should be able to translate this in Crowdin. We generally sync translations back into our repo from Crowdin when we cut release candidate branches as part of our regression testing.

@cscharf  This string no show up in Crowid:

image

**Comment by cscharf** [comment]
Ah, sorry about that @vins345 , we have't sync'd yet so the new strings aren't in Crowdin yet. I'll schedule a sync with our team early next week.

**Pull request closed without merging**
