### PR TITLE
Disables autofill when autocomplete="off" is detected

### LINKED ISSUE #1469: [Major annoying] Bitwarden does not obey autocomplete="off"
I have an issue that Bitwarden for Chrome does not obey autocomplete=off for input fields. This is very annoying for example when moderating other user accounts and it resets their username to my own.

`<input type="password" autocomplete="Off" />`

### PR DESCRIPTION
**Pull request by wusatosi**
This pull request fixes #1469.

## The problem this pr is trying to solve:
As described in #1469, currently, the plugin does not respect [autocomplete=off attribute](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#Disabling_autocompletion).

## Changes made:
On "client" side, autofill.js, I altered some code for collecting autocompletion attribute. 
On "server" side, autofill.service.ts, I added rules to prevent autofill service from generating auto-fill action scripts when this attribute is set to "off".

## Testing
I have personally performed some integration testings on some custom htmls with this attributes.

### CODE REVIEW

**Comment by wusatosi** [comment]
This fix has been tested by myself on a [demo site](http://demo.litecart.net/admin/?app=users&doc=edit_user) from the original issue (https://github.com/bitwarden/browser/issues/1469#issuecomment-753497676).

**Comment by kspearrin** [comment]
This will break a whole host of websites that users expect to autofill. For example, banks often will put autocomplete="off" on password fields so prevent the browser from saving the users password. Users still expect Bitwarden to autofill these fields.

Here's one example: https://www.wellsfargo.com/

**Comment by wusatosi** [comment]
> This will break a whole host of websites that users expect to autofill. For example, banks often will put autocomplete="off" on password fields so prevent the browser from saving the users password. Users still expect Bitwarden to autofill these fields.
> 
> Here's one example: https://www.wellsfargo.com/

This is a valid point, maybe we should introduce an option to config it? Tho this might be to confusing to communicate to our users.

**Comment by kspearrin** [comment]
> 
> 
> > This will break a whole host of websites that users expect to autofill. For example, banks often will put autocomplete="off" on password fields so prevent the browser from saving the users password. Users still expect Bitwarden to autofill these fields.
> > Here's one example: https://www.wellsfargo.com/
> 
> This is a valid point, maybe we should introduce an option to config it? Tho this might be to confusing to communicate to our users.

You might as well just use the existing custom fields and URI match detection options.

**Pull request closed without merging**
