### PR TITLE
Keyboard up/down arrow navigation

### PR DESCRIPTION
**Pull request by respawned86**
This adds keyboard navigation using up/down arrow keys to navigate the lists.

Similar functionality is available by using the "tab" key, however, this is a precursor for my next addition, which is to add support left/right navigation to select the action buttons on a cipher row.

Tab functionality is unchanged with this pull request.

### CODE REVIEW

**Comment by tompoole** [comment]
I have nothing to add to this PR, but thank you for implementing this. I find the tab support quite clunky and it doesn't work in Firefox. Hope this gets merged.

**Comment by cscharf** [comment]
Thank you @respawned86 for the PR! We will review this in the next couple of weeks (we have a lot of folks out on vacation at the moment).

**Comment by respawned86** [comment]
@tompoole, thanks... I recently changed from LastPass to Bitwarden and was frustrated about the lack of keyboard support, so I decided to do something about it :)

I am working on left/right navigation right now, and plan to extend the functionality to other areas of the browser extension.

@cscharf, I will await it eagerly, but fully understand that people are on vacation right now.

This is BTW my first time with Angular, so please feel free to give me pointers, I am always happy to learn.

**Review by eliykat — COMMENTED** [review]
Hey @respawned86, I just reviewed your other keyboard shortcuts PR, so I thought I'd catch up on this one as well. I agree this would be a great addition, and I like the idea of using right/left keys for forward/back navigation as well.

However, I think the implementation approach needs a re-think. This is a fairly manual and code-heavy solution: you have 2 directives plus a service, you're adding bindings to every item on a list which are going to be updated every change detection cycle, and you have to manually configure `navIndexes` for every navigable item (even if `ngFor` loops make this a little easier).

I get the feeling that this may be a solved problem already, and if we can use an existing solution or pattern, it might make for a cleaner implementation. For example, can we manipulate the native tabindex behaviour, or does the Angular a11y library have any solutions? e.g. https://indepth.dev/posts/1147/doing-a11y-easily-with-angular-cdk-keyboard-navigable-lists.

I don't know what the answer is, this is just some general feedback and ideas. I'm open to discussing it further or considering any solutions you find or come up with.

A few other high level notes:
* In the My Vault page, arrow nav does not move between the different sections. It seems to hit the end of a section (e.g. "Types") and then gets swallowed. If I press down 5 times, I have to press up 5 times before it starts moving back up the list.
* The final solution should support the Settings and Options pages as well, given that they're a list layout. I'm not sure about Generator, maybe we leave it to the tab key because it doesn't really have any list navigation on it. I'm open to suggestion here.
* You mentioned "Tab functionality is unchanged with this pull request". I'm not sure if you plan to change it in a future PR? Tab navigation is a web standard, so any changes you make here should be in addition to tab navigation, not replacing it.
* If you add any services, they should be added via Angular's [Dependency Injection](https://angular.io/guide/dependency-injection) system, not created in the component itself. In the browser client, services are configured in `services.module.ts` (short-lived in the popup only) or in `main.background.ts` (long-lived, will run in the background even if the popup is closed). This is just general feedback as you mentioned its your first time with Angular.

Thanks again for the PR! I think it would be a great feature so I hope you keep working on it.

**Comment by eliykat** [comment]
I'm closing this due to inactivity and conflicts. If you'd like to work on this, please open a new PR with no merge conflicts that takes into account the feedback above. Thank you!

**Pull request closed without merging**
