### PR TITLE
[PS-497] Change `<content>` to `<main>`, make it explicitly non-focusable

### PR DESCRIPTION
**Pull request by patrickhlauke**
## Type of change

- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Some browsers (Firefox, upcoming versions of Chrome https://bugs.chromium.org/p/chromium/issues/detail?id=585413) make containers with `overflow: auto` / `overflow: scroll` (and the `-x` / `-y` variants) keyboard-focusable. This leads to a very awkward experience for assistive technology users navigating through the extension window, as for every view, the entire `<content>` container receives focus (and screen readers try to announce all its content in one go) before you reach the actual first control. To counteract this behavior, this adds an explicit `tabindex="-1"` to these elements.

As an aside, from a semantic point of view, `<main>` is more appropriate than `<content>`, so changing this as well as part of the PR (though this doesn't affect the reported behavior).

## Code changes

* Change `<content>` to `<main>` element across the various `.html` templates (see https://github.com/bitwarden/browser/pull/2245#issuecomment-1104553312)
* Add `tabindex="-1"` to all instances of the `<main>` element 
* Change `app.components.ts` to swap out the `<main>` used as a wrapper for the entire content of the extension with a generic `<div>` container (as you can't have nested main elements, and semantically this wasn't really a main, but generic container)
* Update `base.scss` and `pages.scss` accordingly to target the new generic `<div>` wrapper and swap out references to `content` element with `main` element

## Screenshots

No visual change

## Testing requirements

Test using a Canary version of Chrome, or current Firefox. Use a screen reader, navigating with `Tab`/`Shift + Tab` to verify that `<content>` doesn't receive focus on its own anymore (and attempts to blurt out the entire content of the view in one go). Alternatively, force some prominently visible focus outline styles to visually verify that `<content>` no longer receives keyboard focus.

## Before you submit

- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Video showing the issue - navigating through the extension's popup in Chrome Canary (99.0.4783.0) using NVDA - and the behaviour after the change in this PR. Note how currently, when Tab-bing forward from the Back button, `<content>` receives focus and the entire content of this container is being read out by NVDA. After the fix, focus goes, as expected, from the Back button to the first control in the view.

https://user-images.githubusercontent.com/895831/147284752-6e73806b-6c2c-45cd-989a-966cb45fa154.mp4

**Comment by patrickhlauke** [comment]
Any news on this? It'll become relevant soon once the Chrome behaviour making `overflow: scroll` etc container focusable by default (and is already an issue now in Firefox)

**Comment by patrickhlauke** [comment]
It seems Chrome have currently held off making the change where containers with `overflow: auto` etc are automatically keyboard focusable. However, the issue is visible right now in Firefox (which is the first browser that pushed for this heuristic behavior).

Video showing current stable Firefox, current stable release of Bitwarden (1.57.0), and NVDA. Note that tabbing to the content panel leads to the `<content>` itself receiving focus, and the screen reader blurting out *all* of the content of it in one big go. Adding `tabindex="-1"` to make it explicitly non-focusable solves this issue (and, as there are focusable elements inside the `<content>` panel, this won't cause issues for keyboard users not being able to scroll the panel - the reason for the heuristic - as they can already set focus to elements inside the scrollable container, at which point their regular cursor keys etc to scroll will work).

https://user-images.githubusercontent.com/895831/164178356-791e75b9-4a6a-4bd0-8156-446a70dbe4a1.mp4

Would be good to get this relatively simple and harmless PR merged. /cc @eliykat

**Comment by eliykat** [comment]
Thanks for the follow-up @patrickhlauke. Maybe we shouldn't even be using `<content>` elements? The [MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/content) says it's for ShadowDOMs, not regular content, and is deprecated. It seem like `<main>` is more appropriate ([ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main)). What do you think? Could you try with `<main>` and see if the `tabIndex` is still required?

**Comment by patrickhlauke** [comment]
@eliykat the focusing behavior/heuristic comes purely from the `overflow:...` that's defined here, regardless of the actual HTML element.

but yes, separately (from a semantic point of view), `<content>` is really only treated currently as a generic `<div>`, and it probably makes semantic sense to change it to `<main>` (but it won't solve the problem). I can do that as part of this PR as well as an aside...

**Review by eliykat — CHANGES_REQUESTED** [review]
Gotcha, I missed that in your initial explanation. Definitely worth updating the html while we're here though.

There are also various styles that use `content` in their selector which will also need updating. Looks like `base.scss` and `pages.scss`, but please double check the others.

**Comment by patrickhlauke** [comment]
@eliykat doh, schoolboy error on my part. thought i'd sneak that simple change in without testing/considering the consequences. 

now gone through this properly (and tested):

* changed the scss files (the two files you mentioned where the only place where styles for `content` element were defined)
* changed `app.component.ts` as it was already wrapping the entire content of the extension in a `<main>`, and you can't have more than one `<main>` (and certainly not nested ones). semantically, that outer `<main>` wasn't doing anything, so swapped it for a generic `<div>` container.

**Review by eliykat — APPROVED** [review]
Good work thank you, and good pick up on the existing `<main>`, I hadn't noticed that.

**Pull request merged**
