### PR TITLE
Corrections + new strings

### PR DESCRIPTION
**Pull request by maxlandry**
Correction of spelling mistakes + add strings (lines 626 to 650)

### CODE REVIEW

**Comment by kspearrin** [comment]
@Primokorn care to review?

**Comment by Primokorn** [comment]
@maxlandry Thanks for your help. I would change this translation into `b18fac9`though:
> "addLoginNotificationDesc": {
> "message": "La \"Notification de demande d'ajout d'identifiant\" apparait automatiquement pour vous demander d'enregistrer dans votre coffre les identifiants que vous ~~les~~ utilisez pour la première fois."

**Comment by maxlandry** [comment]
@primokorn You're right! Absolutely!

**Comment by kspearrin** [comment]
@maxlandry Are you going to make that change?

**Comment by maxlandry** [comment]
Sorry! I thought it was already done! I'm still not very familiar with GitHub!

It's done now!

**Comment by kspearrin** [comment]
Thanks!

**Pull request merged**
