### PR TITLE
Add copy action button for TOTP code

### PR DESCRIPTION
**Pull request by danielwaltz**
Adds support for quickly copying the TOTP code for use when logging in to a site that utilizes 2FA.

image

### CODE REVIEW

**Comment by danielwaltz** [comment]
As I was working on this it occurred to me that a lot of users probably aren't using this feature, so it might be better to show/hide it instead of simply disable it.

That said, if you see it all the time and it's always disabled it might put a bug in their ear that "hey, maybe this is something I should actually use"... which I see as a good thing. It's extremely secure and to use it requires supporting this amazing suite of apps.

**Comment by kspearrin** [comment]
The reason this has not been added in the past is that we did not want to add a 4th button to the row. It is overcrowded as it is. We need to come up with a better solution, such as added a right-click context menu or something similar that holds all of the options.

**Comment by danielwaltz** [comment]
The only thing about a right click menu is for touch screen users that's a pain in the butt. It's not that I expect many people to be interacting with this extension using only touch, but it's just something I've conditioned throw a red flag in the back of my head when I work on apps.

If we could possibly allow for squeezing just one more button in there we could have an action button that triggers a dropdown menu for copying any of the rest of the sub items, including the TOTP code.

That said if an extra button is a hard pass that's perfectly fine too. I can try to think of another more convenient solution to grab at least the TOTP code. I may take a look at autofill for it or something. For me that's the part of using the extension that causes me the most friction, so I wanna try to do something about it if I can!

**Comment by kspearrin** [comment]
I am thinking somehow we add a button which drops down with additional options, like our website.

**Comment by danielwaltz** [comment]
Cool cool. Would that replace all the action buttons currently there? I could possibly look into setting that up, but I think I'd prefer to do it in another PR as it's not really related to TOTP directly anymore. I'll go ahead and close this.

Thanks for the responses!

**Comment by kspearrin** [comment]
I would say that we keep a few action buttons that are most used, like copy password and view. Just keeping the max at 3 buttons total.

**Pull request closed without merging**
