### PR TITLE
Tweak colours for better contrast

### PR DESCRIPTION
**Pull request by patrickhlauke**
## Type of change
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
Currently there are a large number of instances where text colour has insufficient contrast against its background (below 4.5:1). Likewise, the scrollbar is very faint and doesn't reach a high-enough contrast (3:1). For a more in-depth explanation, see https://github.com/bitwarden/browser/issues/2235

This SC subtly tweaks the light and dark theme colours to boost contrast just to/over 4.5:1 for text, and 3:1 for the scrollbar. It introduces a few new variables, mainly because it's not possible to find a suitably vibrant warning red colour in the dark theme that works both as a foreground colour (for the delete buttons) and as backdrop for the warning toast - so this introduces specific separate variables to control the toast styling.

Closes https://github.com/bitwarden/browser/issues/2235

## Code changes

* **variables.scss:** subtly tweak colours, add new variables for toasts, specify the values of these new variables in the different themes
* **plugins.scss:** use the newly defined variables to declare colours for toasts; also explicitly styles the new "x" close button

## Screenshots
Comparison of current 1.55.0 (left) and the changed colours from this PR (right). The changes are, for the most part, very subtle (with exception of the scrollbar, which is likely the most visible/contentious of the changes).

EDIT from @djsmith85 : Removed some images (possibly exposing sensitive data) and copied them to Asana task: https://app.asana.com/0/1169444489336079/1201536755162434/f for internal review

## Testing requirements

Verify that all possible colour combinations used (including when hovered/focused) are sufficient (4.5:1 for text, 3:1 for important non-text content - disabled controls are exempt). Suggest using a tool like the [Colour Contrast Analyser](https://github.com/ThePacielloGroup/CCAe)

## Before you submit
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

### CODE REVIEW

**Comment by patrickhlauke** [comment]
To be clear, I'm aware that this type of change is likely to cause much more discussion and pushback than some of my earlier PRs, as this directly impacts visual style (and possibly core brand colours used in other places as well). Nonetheless, it would be good to meet the minimum WCAG 2.1 thresholds for text and non-text contrast, and perhaps making the same changes upstream to cascade through other properties/products that use the same brand colours?

**Comment by djsmith85** [comment]
Hi @patrickhlauke one of our designers @danielleflinn made some adjustments to align the browser dark theme with colors used in the dark web theme here https://github.com/bitwarden/browser/pull/2241.

We are waiting on approval for the brand color changes.

Your changes to the light theme look good.

We decided to go with a toastTextColor instead of changing the toasts background as you did.

As we've recently introduced prettier to format our files, please have a look at https://github.com/bitwarden/browser#prettier to sync up with the current master. Probably good to merge up to the commits mentioned and then it's going to be easier to fix any merge conflicts to fully update to master. Let me know if you need any help with that.

**Comment by patrickhlauke** [comment]
@djsmith85 I *think* i've now done the necessary/suggested changes, but admittedly lost track now of what's in and what's out in this PR. will need to do a run-through to check...

**Comment by patrickhlauke** [comment]
if it's easier to abandon this PR and start a fresh one, let me know (and probably more specifically, which aspect can be salvaged from this, as I'm now not sure if I'm undoing stuff in the dark theme by accident - did you just want the changes from the light theme in this PR?)

**Comment by djsmith85** [comment]
@patrickhlauke Thank you for tackling this. We definitely would like to align these changes in other clients, just to have that consistency and accessibility everywhere. To aid with client parity and also to include your a11y specific changes, we've started a discussion to create basic components (buttons, label, dropdown, etc.) which can be re-used across all web-based clients. This effort will obviously take some time to get implemented.

We are always grateful for any kind of contribution from our community. Depending on the amount of work (smaller changes) and what other efforts internally are going on, we might ask the contributor to make additional changes, but it's still up to the contributor, and it stays fully voluntary.

I have to admit that the migration to prettier hasn't been as smooth as we had hoped for. So in this case it might be easier to create a new PR fresh off of master and re-create your changes. We'd like to include the changes on the light theme. The changes to the solarized theme, as this is specific to browser, would also be nice to have, but we are still awaiting on approval for the brand color changes. Maybe you could split those up into 2 PRs and we can get the light theme changes merged quickly and have the other up for discussion/approval with design.

**Comment by patrickhlauke** [comment]
sorry, didn't mean to sound like i was moaning/complaining. genuinely just wondering out loud if i should redo the PR as i myself have now lost track exactly of what is/isn't fixed by it. i'll have a look at what the latest state is after the recent change to align the dark theme, and see what take a fresh look at the things I did in this PR and what to salvage/bring over into a new PR :+1:

**Comment by djsmith85** [comment]
No need to apologize, I didn't think you were complaining. I was also just trying to say that we are aware that the other clients also should be as accessible as the browser extensions is. Especially with the great work you've been doing in it. Thank you again, for tackling that and we really appreciate it. 

Over the last 1 1/2 months we've been doing a lot of tech debt related changes which has resulted in quite an extensive change in the codebase. This obviously makes it harder to keep track and PR's up to date. In this case I agree, it might be good to create a new PR to have a clean slate to start with. Sorry for the inconvenience.

**Comment by patrickhlauke** [comment]
no worries, group hug :)

**Comment by patrickhlauke** [comment]
I'm going to close this as stale, and make a fresh clean start at some point (sorry, it's been sitting in my open tabs for so long, but haven't found the time to look at this in detail again and match up what's changes already since I made it)

**Comment by djsmith85** [comment]
@patrickhlauke No problem, and thank you very much for all the work on making Bitwarden more accessible.

**Pull request closed without merging**
