### PR TITLE
Add German translation files

### PR DESCRIPTION
**Pull request by KarimGeiger**
This will add German translation to the bitwarden extension. I've also included the two store description files.

### CODE REVIEW

**Comment by kspearrin** [comment]
Thank you!

**Comment by kspearrin** [comment]
@KarimGeiger Looks great. Only issue I see is on the help & feedback page the back button for settings spills over into the title. Not sure if there is anything we can do to get a shorter version of "Settings", but if not I think we can live with it :)

deissue

**Comment by KarimGeiger** [comment]
Hmm no I don't think you can change anything without losing its meaning, since Einstellungen is the only valid translation in that context. But we could remove the Feedback and just call it Hilfe (=help) as this is what it's primarily about.

**Comment by kspearrin** [comment]
@KarimGeiger Could you please email from the contact form on the website, https://bitwarden.com/contact/?  I'm trying to collect all of the translation contributors contact information so that I can keep you up to date via email when translations change. Thanks.

**Pull request merged**
