### PR TITLE
Added ability to disable the lock icon

### PR DESCRIPTION
**Pull request by ajayyy**
It will show the gray icon instead.

The red lock icon bothers me as it feels like it is a notification. So, this PR just adds an option to disable it.

image

image

Depends on https://github.com/bitwarden/jslib/pull/54

### CODE REVIEW

**Comment by ajayyy** [comment]
The build has failed since it requires the jslib PR to be merged first.

**Comment by ajayyy** [comment]
Any update?

**Comment by kspearrin** [comment]
We do not plan on merging this feature at this time. We will keep it open, however.

**Comment by ajayyy** [comment]
Any specific reason?

**Comment by ajayyy** [comment]
Since this my PRs are not going to be merged soon, I will be maintaining a separate fork with these changes.

https://github.com/ajayyy/browser/releases/tag/1.46.1

**Comment by eliykat** [comment]
Hi @ajayyy, thanks for the PR! I'm reviewing old PRs and raised yours for discussion with our Product team. We agree that red-on-blue isn't a great colour combination, however our preferred solution is to change the colour of the lock icon. I can confirm this is on our roadmap for future development.

We don't see enough of a need to add an option to disable the lock icon altogether, and hopefully a change in colour will make it a bit easier on the eyes.

If you'd like to contribute in the future, please consider posting in the [Github Contributions](https://community.bitwarden.com/c/github-contributions/7) section of our Community Forums before you start work, so that we can make sure it's suitable for merging.

**Pull request closed without merging**
