### PR TITLE
Add Chinese Translations

### PR DESCRIPTION
**Pull request by felixqu**
Add Chinese translations and fixed an translation error.

### CODE REVIEW

**Comment by kspearrin** [comment]
@felixqu Are you interested in doing the translations for the mobile app as well? They are mostly the same strings. We've had a lot of Chinese users lately asking for it. If so I can get you the necessary instructions for that since the process is different.

**Comment by felixqu** [comment]
Of course I'm interested. Please let me know what I can do.

**Comment by kspearrin** [comment]
The mobile app uses Resource XML files (resx) for translations. You can find theme here: https://github.com/bitwarden/mobile/tree/master/src/App/Resources

To do the Chinese translations you'll need to copy/paste the base English file (`AppResources.resx`), rename it to `AppResources.zh-Hans.resx` (Chinese, simplified) and start translating the `<data>` => `<value>` elements. Please leave the `<comment>` elements in English.

Let me know if you have any questions.

**Comment by felixqu** [comment]
Do I need to copy/paste the file AppResources.Designer.cs to AppResources.zh-Hans.Designer.cs, just like AppResources.es.Designer.cs?

**Comment by kspearrin** [comment]
No, just leave that file. You'll notice that the `AppResources.es.Designer.cs` one is just an empty file that gets generated for some reason.

**Comment by kspearrin** [comment]
@felixqu Could you please email from the contact form on the website, https://bitwarden.com/contact/?  I'm trying to collect all of the translation contributors contact information so that I can keep you up to date via email when translations change. Thanks.

**Pull request merged**
