### PR TITLE
Don't use deprecated initKeyEvent() for autofill

### LINKED ISSUE #2000: Firefox: Dependency on KeyboardEvent.initKeyEvent causes auto-fill breakage in Nightly
## Describe the Bug

In `src/content/autofill.js`, there is a dependency on `KeyboardEvent.initKeyEvent` for Firefox:

https://github.com/bitwarden/browser/blob/ef4dddcef3115e973b133d0b473c315425ca43b4/src/content/autofill.js#L841-L844

Given this was a Firefox-only thing and it's been causing web compatibility issues, [it was removed yesterday](https://bugzilla.mozilla.org/show_bug.cgi?id=1717760), shipping in today's Nightly. Unfortunately, this breaks Bitwarden's auto-fill, as the codepath above only checks for `isFirefox`, and does not check if `initKeyEvent` is defined or not.

## Steps To Reproduce

1. Upgrade to Firefox Nightly 2021-08-10 or newer.
2. Try using the Auto-Fill keyboard shortcut.

## Expected Result

Auto-filling fields.

## Actual Result

Nothing happens. 

## Environment

- Browser: Firefox Nightly 93a1, >= 2021-08-10
- Build Version (go to "Settings" → "About" in the app): 20210810094908

### PR DESCRIPTION
**Pull request by mathewhodson**
This fixes #2000

### CODE REVIEW

**Comment by jonathonf** [comment]
Can confirm this is working with 93.0a120210810213316

**Comment by streetwolf** [comment]
Can I download the version of BW that contains this patch.  I use Nightly and really need this.

**Comment by jonathonf** [comment]
@streetwolf I can send you an unsigned XPI that you can install via `about:debugging`, though that would be very much an "at your own risk" situation.

**Comment by streetwolf** [comment]
Sure.  Send it my way.  I’ll let you know the results.


……..…….
Regards,

Gary  ( ͡° ͜ʖ ͡°)

**Review by MGibson1 — APPROVED** [review]
This looks good to me. Thank you, it looks like this has been teetering on the edge of support for a while now.

@cscharf @bitwarden/dept-qa I don't think this is critical to get into this release since the nightly just dropped support (FF nightlies are usually a few months out from stable). However, if you think there's capacity for adding this to the rc branches cut last night it's probably a good addition.

**Comment by MGibson1** [comment]
Once this is merged into master it should also create build artifacts that can be installed in the same location.

**Comment by jonathonf** [comment]
@streetwolf I edited in [the link](https://send.bitwarden.com/#68sMs78NYkuHma2BANjXbg/pCVMAYo0AKUI3Oy5ROq_VA) in my previous post (notification emails won't show those edits...) so here it is again. :)

**Comment by streetwolf** [comment]
So far so good.  All my sites can be filled both manually and with autofill.  It also seems that the forms are being filled quicker than before.


……..…….
Regards,

Gary  ( ͡° ͜ʖ ͡°)

**Comment by cscharf** [comment]
@MGibson1 , let's please ensure we have the linked Github issue in Asana and is queued up for testing, but not in `rc`, we can merge this into `master` and leave it for the next release. The QA team has started regression testing already for the upcoming release.

**Comment by denschub** [comment]
@MGibson1 just a heads up:

> FF nightlies are usually a few months out from stable

Nightly 93, which breaks Bitwarden, will go into Beta on September 6 and most likely be release on October 5. So that's ~8 weeks.

**Comment by cscharf** [comment]
> Nightly 93, which breaks Bitwarden, will go into Beta on September 6 and most likely be release on October 5. So that's ~8 weeks.

We'll definitely be able to roll it out before then.

**Comment by streetwolf** [comment]
As already stated the unsigned version with the patch hasn't caused me any problems so far.  Nice job.  Hope the signed version becomes available soon.

**Comment by MGibson1** [comment]
We only sign our release builds, but here is the link to the Github actions build for Firefox: https://github.com/bitwarden/browser/suites/3472198561/artifacts/82556656

**Comment by streetwolf** [comment]
When you release the next update BW as I understand things it will be without this patch.  Will there be a way to get the latest BW updates containing the patch or will I have to remain on what I already have?  Again many thanks for taking on this issue so quickly.


……..…….
Regards,

Gary  ( ͡° ͜ʖ ͡°)

**Comment by MGibson1** [comment]
The master branch already contains all the code which will be included in the next release. You've already got the good stuff :)

That being said, please recognize that these non-release builds do not go through our regression testing process and many may be totally untested. Expect more issues than with an actual release build.

**Comment by Movisivi** [comment]
> 
> 
> We only sign our release builds, but here is the link to the Github actions build for Firefox: https://github.com/bitwarden/browser/suites/3472198561/artifacts/82556656

So I installed this. Working fine thanks to all involved. Am I good to stay here and it'll auto update?

**Comment by Caspy7** [comment]
It was mentioned in another issue but not this one, there is a simpler resolution to this problem: Go to `about:config` in the URL bar, find `dom.keyboardevent.init_key_event.enabled` and toggle it to true.

Apparently the deprecated API in question has not been removed from the code yet, just disabled. By the time it is removed, release Bitwarden will [hopefully] have updated to mitigate the issue.

**Comment by BBaoVanC** [comment]
Was this included in 1.52.0? Firefox auto-updated it to the latest version and autofill stopped working again (but using the artifact mentioned here works)

**Comment by denschub** [comment]
> Was this included in 1.52.0?

No, it was not: https://github.com/bitwarden/browser/blob/v1.52.0/src/content/autofill.js#L843

**Comment by bb010g** [comment]
How do merges into the `rc` branch work?

**Comment by eliykat** [comment]
Thank you @Caspy7 for the workaround. I confirm this wasn't included in 1.52.0 but will be in the next release, per @cscharf's [comment above](https://github.com/bitwarden/browser/pull/2001#issuecomment-896956199).

@bb010g: we develop off the `master` branch. 1-2 weeks before a release, we cut `rc` (release candidate) branches for each repo, and those branches are used for regression testing and deployment (not `master`). The date that we cut `rc` branches is the effective cut-off date for features and fixes.

**Pull request merged**
