### PR TITLE
Added russian language

### PR DESCRIPTION
**Pull request by sersoftin**
I translate this ext. to russian language.

### CODE REVIEW

**Comment by kspearrin** [comment]
Thanks for this. It would be great if there was someone else that knows Russian well that could review this for me. I'll leave it open for a bit to see if we can find someone.

Also, I noticed that there were several strings in the codebase that still haven't been moved to the locales. I'll plan on adding those soon, but whenever I do we'll need to update this localization to include their translations as well.

**Comment by sersoftin** [comment]
@kspearrin yes. For example:
1) "Copy Password" hint in site list;
2) All notices (after add site, etc).

**Comment by sersoftin** [comment]
Moreover I don't know how translate "site" in this context. Site - account on web-page (login/password pair).

**Comment by sersoftin** [comment]
@ArtemNikolaev help @kspearrin with Russian locale.

**Comment by kspearrin** [comment]
Also, there are some the CAPTIONS and COPY files for the store could use these translations as well. https://github.com/bitwarden/browser/tree/master/store/en-US

Just add a new folder called `ru` for them. Don't worry about the screenshots and assets. I will update them with your translation file text when done.

**Comment by sersoftin** [comment]
@kspearrin mission completed :-)

**Comment by kspearrin** [comment]
Thanks. Keep on the lookout for the updates to the rest of the locale strings that need to be added. I'll try to work on that soon.

**Comment by kspearrin** [comment]
@sersoftin  I finally finished add all the missing translations to the en locale. Can you add them to ru when you get some time?

**Pull request merged**
