### PR TITLE
Grouping by organization.

### PR DESCRIPTION
**Pull request by iineva**
Updates:
* Grouping organization.
* When user click add button, will auto select current organization to Ownership filed.

UI Update:
image

image

i18n:
* Default all to English
* zh_CN
* zh_TW
* ja

### CODE REVIEW

**Comment by kspearrin** [comment]
If we did groupings by organization I think we would just want to do that on the collection listing

**Comment by iineva** [comment]
Like this?
image

**Comment by kspearrin** [comment]
I was thinking the navigation tree would be more like:


- Org A
  - Collection 1
    - Collection 1.1
      - Item C
      - Item D
    - Collection 1.2
      - Collection 1.2.1
      - Item D
    - Item X
    - Item Y
  - Collection 2
      - Item A
      - Item B
- Org B
  - Collection B1
    - Item G
    - Item H


This would need to be implemented across all clients as well, so might need more thought.

**Comment by djsmith85** [comment]
Hi @iineva , thanks for your submission! If you're still interested in progressing this PR, please:
* review/respond to any outstanding change requests or questions
* reply here and tag me (@) so that I can mark it for further review

As this PR is more than 12 months old, I'll close it for now. However, this is just housekeeping. We encourage our community members to get involved and make contributions, so you can comment here even after it's closed and I'll reopen it if required.

**Pull request closed without merging**
