### PR TITLE
Create french messages.json

### PR DESCRIPTION
**Pull request by Primokorn**

### CODE REVIEW

**Comment by kspearrin** [comment]
Hey thanks for this. Could you also add the store translations as well? see https://github.com/bitwarden/browser/tree/master/store

**Comment by Primokorn** [comment]
Sure, 2 new PRs added.

**Comment by kspearrin** [comment]
@Primokorn  I finally finished add all the missing translations to the en locale. Can you add them to fr when you get some time?

**Comment by Primokorn** [comment]
No problem. PR done.

**Pull request merged**
