### PR TITLE
Updated expiration year placeholder text to be dynamic

### PR DESCRIPTION
**Pull request by AmGarera**
Updated Example text to be dynamic to current year using New Date(); and then a Date pipe to display properly in the UI.

### CODE REVIEW

**Comment by AmGarera** [comment]
> Seems like this needs to be added to all client apps through the base component in jslib.

I don't see add-edit.component.html in the base component in jslib, just add-edit.component.ts. Otherwise I'd make the requested changes.

**Comment by kspearrin** [comment]
Yes, you would add the `currentDate = new Date();` part to the base file is jslib and then apply the UI parts in each client. This is the pattern we use for all JS-based angular apps for Bitwarden.

**Comment by AmGarera** [comment]
That makes more sense now, I can do that. Thank you for the quick response and clarification! 😄

**Comment by AmGarera** [comment]
PR submitted to jslib library - link [here](https://github.com/bitwarden/jslib/pull/120)

**Pull request merged**
