### PR TITLE
Old Icons Replaced by New Ones

### PR DESCRIPTION
**Pull request by Nihal247**
I closed that older PR, and opened this one because it didn't showed me desired results.

### CODE REVIEW

**Comment by Nihal247** [comment]
chrome-icon128
icon64
safari-icon256
windows-icon300
After changes (icons folder)☝

Before changes (icons folder)👇
chrome-icon128
icon64
safari-icon256
windows-icon300

**Comment by Nihal247** [comment]
I hope @eliykat, it's much clear now?

**Comment by cscharf** [comment]
Thanks @Nihal247 , can you please revert changes to AppxManifest.xml as there doesn't appear to be any changes to that file, but to keep the git commit history clean it would be helpful to revert that file.

**Comment by Nihal247** [comment]
Sorry @cscharf, but I uploaded AppManifest.xml with all the icons, so I couldn't revert a specific change (or I just don't know how to revert a specific change!). If you know how to revert it back, you may do it,

Thanks! (and Sorry!)

**Comment by eliykat** [comment]
You can use `git checkout` on an individual file to check out a copy of that file from another branch: `git checkout <branch> <file>`
For example: `git checkout upstream/master store/windows/AppxManifest.xml`
Then commit your changes and push. That should revert all changes to that file only, and it'll disappear from this PR.

**Comment by Nihal247** [comment]
I tried it, but it's giving `error: pathspec 'upstream/master' did not match any file(s) known to git
`

**Review by eliykat — APPROVED** [review]
It can be tricky to guess how you've got your git remotes set up. I've just done it for you :)

Approving based on the discussion above. Thanks for the contribution @Nihal247 !

**Review by eliykat — APPROVED** [review]

**Pull request merged**
