### PR TITLE
Default usernames

### PR DESCRIPTION
**Pull request by michalchecinski**
Community forum thread: https://community.bitwarden.com/t/default-usernames/19071

jslib PR: bitwarden/jslib#286
web PR: bitwarden/web#854
Server PR: bitwarden/server#1170

### CODE REVIEW

**Comment by eliykat** [comment]
Thanks for the PR @michalchecinski. We'll be reviewing various community PRs after the upcoming release. In the meantime, can you please tidy this up for further review by removing all changes to `messages.json` files, except for `en/messages.json`. All other localization is handled by CrowdIn (see README.md for more info).

**Comment by michalchecinski** [comment]
@eliykat I've fixed translation :)

**Review by eliykat — CHANGES_REQUESTED** [review]
Please see general comments on jslib PR. Browser also has a few extra considerations due to the reduced screen real estate we have to work with.

**Comment by eliykat** [comment]
I'm closing this due to inactivity and per the discussion [here](https://community.bitwarden.com/t/default-usernames/19071/37).

**Pull request closed without merging**
