### PR TITLE
Replaced Old Icons by New Ones

### PR DESCRIPTION
**Pull request by Nihal247**
Old Bitwarden icons replaced by new ones! (dimensions are same)

### CODE REVIEW

**Comment by eliykat** [comment]
Can you please include before/after comparisons in your PR description, and explain what changes you've made and why?

**Comment by Nihal247** [comment]
Before:
https://raw.githubusercontent.com/bitwarden/browser/294e7c3b8d8e7ae6d71433ea4305ce37f8ec3c3f/store/icons/chrome-icon128.png

After:
https://raw.githubusercontent.com/bitwarden/browser/a3c00eaea319fb60d3bfa28f48c308dd2526220e/store/icons/chrome-icon128.png

File: chrome-icon128.png
Location: https://github.com/bitwarden/browser/blob/master/store/icons/chrome-icon128.png

**Comment by Nihal247** [comment]
Before:
https://raw.githubusercontent.com/bitwarden/browser/master/store/icons/icon64.png

After:
https://raw.githubusercontent.com/Nihal247/browser/master/store/icons/icon64.png

File: icon64.png
Location: https://github.com/bitwarden/browser/blob/master/store/icons/icon64.png

**Comment by Nihal247** [comment]
Before:
https://raw.githubusercontent.com/bitwarden/browser/master/store/icons/safari-icon256.png

After:
https://raw.githubusercontent.com/Nihal247/browser/master/store/icons/safari-icon256.png

File: safari-icon256.png
Location: https://github.com/bitwarden/browser/blob/master/store/icons/safari-icon256.png

**Comment by Nihal247** [comment]
Before:
https://raw.githubusercontent.com/bitwarden/browser/master/store/icons/windows-icon300.png

After:
https://raw.githubusercontent.com/Nihal247/browser/master/store/icons/windows-icon300.png

File: windows-icon300.png
Location: https://github.com/bitwarden/browser/blob/master/store/icons/windows-icon300.png

**Comment by Nihal247** [comment]
Before:
https://raw.githubusercontent.com/bitwarden/browser/master/store/windows/Assets/icon_150.png

After:
https://raw.githubusercontent.com/Nihal247/browser/master/store/windows/Assets/icon_150.png

File: icon_150.png
Location: https://github.com/bitwarden/browser/blob/master/store/windows/Assets/icon_150.png

**Comment by Nihal247** [comment]
Before:
https://raw.githubusercontent.com/bitwarden/browser/master/store/windows/Assets/icon_44.png

After:
https://raw.githubusercontent.com/Nihal247/browser/master/store/windows/Assets/icon_44.png

File: icon_44.png
Location: https://github.com/bitwarden/browser/blob/master/store/windows/Assets/icon_44.png

**Comment by Nihal247** [comment]
Before:
https://raw.githubusercontent.com/bitwarden/browser/master/store/windows/Assets/icon_50.png

After:
https://raw.githubusercontent.com/Nihal247/browser/master/store/windows/Assets/icon_50.png

File: icon_50.png
Location: https://github.com/bitwarden/browser/blob/master/store/windows/Assets/icon_50.png

**Comment by Nihal247** [comment]
All the 7 files I changed ☝

I changed these because they were old Bitwarden logos, and have replaced it by new ones.

**Comment by Nihal247** [comment]
You may edit the icon I provided for chrome-icon128.png, but rest all the icons are fine.

**Pull request closed without merging**
