### PR TITLE
Updated: Keyboard arrow navigation

### PR DESCRIPTION
**Pull request by matschaffer**
https://github.com/bitwarden/browser/pull/1962 but with master merged and conflicts resolved.

### CODE REVIEW

**Comment by matschaffer** [comment]
I got this to work once but I'm having trouble getting it to work again. It's been ages since I've done chrome extension development so could be I'm holding something wrong.

**Comment by djsmith85** [comment]
@matschaffer Thank you for your contribution and tackling this.

I'm going to set this as a draft until this is ready for review. Please keep in mind, that @eliykat also had some comments on the approach on the original PR.

**Comment by matschaffer** [comment]
Yeah, I agree with @eliykat 's comments, especially after fixing the conflicts for it. The approach here seems pretty invasive.

Ideally this PR would have just been another commit to https://github.com/bitwarden/browser/pull/1962, but I don't have the that permission so I opened this instead. I wouldn't mind just closing this PR, or probably even it's parent PR.

**Comment by eliykat** [comment]
Hey @matschaffer, PRs on this feature are welcome, but I think it would be better to create a new branch. The approach in the original PR is not suitable for merging, so it's not worth trying to resolve conflicts etc. If you'd like to work on this, please submit a new PR which takes into account the feedback in my other comment.

I'll close both this PR and the parent PR given that it's been about 6 months with no further activity. Please tag me in any new PR you open and I'll check it out. Thanks!

**Comment by matschaffer** [comment]
Makes sense to me. Thanks @eliykat !

**Pull request closed without merging**
