### PR TITLE
Use infinite scroll for all cipher lists

### LINKED ISSUE #1597: Performance issues while login or searching with accounts that have access to more than 2000 items
## Describe the Bug

If your account has access to more than 2000 items, the login and search process with the browser extension gets strongly degraded.

## Steps To Reproduce

1. Log into the browser extension.
2. Wait for your account to login around 20/30 seconds.
3. Search for an item in the browser extension.
4. Wait for another 20 seconds for the search process to give you a result.

## Expected Result

Not have to wait between 20 and 30 seconds to log in and a similar amount of time to perform a search.

## Environment

- Operating system: Windows 10
- Browser: Chrome 88.0.4324.96 and Firefox 85.0
- Build Version:  1.47.1 and 1.48.1

## Additional Context

After a successful login with Chrome's browser extension with an account that has more than 8000 items, after 15 minutes of general usage, the overall resource consumption of my laptop was heavily affected. Closing Chrome (and the session) solves the issue almost immediately. Don't have the specific numbers, but could repeat the experiment and document them.

### PR DESCRIPTION
**Pull request by eliykat**
## Objective
Partial solution to #1597: 
> If your account has access to more than 2000 items, the login and search process with the browser extension gets strongly degraded.

This is an issue with the web vault as well, but I thought I'd tackle the browser first and then replicate the solution for the other Angular clients.

For testing purposes, I used a vault with over 8k items.

I'm making this a draft because I want to make sure we're happy with this solution before going further.

## Assessment
In the browser plugin, I think this slowness is largely caused by the number of components rendering on the screen. Search being slow is a red herring - everything is slow. (I measured search using consoleLogService and it's fine, even with a large number of items.)

We only have infinite scroll implemented in the `ciphers` component, but that loads too many items at once (100) and does not unload items as you scroll (so they gradually accumulate, affecting performance). No other component has any form of lazy loading/rendering - so for example, searching will render all the results at once.

## Solution
Our current infinite scroll is fairly bespoke and is limited to one component. I removed it and used the [ngx-virtual-scroller](https://www.npmjs.com/package/ngx-virtual-scroller) library instead:
>This module displays a small subset of records just enough to fill the viewport and uses the same DOM elements as the user scrolls. This method is effective because the number of DOM elements are always constant and tiny irrespective of the size of the list. Thus virtual scroll can display an infinitely growing list of items in an efficient way.

After this change, I was able to navigate the UX and perform basic tasks, including searching, with minimal slowdown. QA can probably advise whether this solves the problem completely or whether we need to find other performance gains elsewhere. Either way, I think this is still a large improvement.

## Code changes
* `package.json`, `package-lock.json`, `app.module.ts` - remove ngx-infinite-scroll and use ngx-virtual-scroller instead
* new `ciphers-list-scroll.component` to implement virtual scroll
  * I'll probably just replace `ciphers-list.component` with this, as by the time I was done I wasn't using the original anywhere
  * note that ngx-virtual-scroller requires an explicit height to be set on the container element and on the item elements, which is why this is done in the component rather than in css
* update all templates to use the `ciphers-list-scroll.component` instead

Related changes to jslib: https://github.com/bitwarden/jslib/pull/299. These changes remove the paging logic from the `ciphersComponent` parent class, which is no longer required.

### CODE REVIEW

**Comment by vincentsalucci** [comment]
Does this also help with the login delay? My guess is that there will need to be some arch changes made to how we do full syncs - thoughts?

Because this PR mentions removing `ngx-inifite-scroll`, it would be nice to also remove [this](https://github.com/bitwarden/browser/pull/1412) change that was specifically made because of the above library. I believe it was only an issue in **production** builds, so doing a few test runs with side-loaded production builds would be great. 

Did you test these improvements on **Chromium, Firefox, and Safari**?

**Comment by eliykat** [comment]
Good point - it doesn't help with the login delay, which still takes about 10-12 seconds with 8k+ items. I agree that's probably a more difficult problem, which I'll look into next. But I thought that this change would be the biggest improvement for the smallest cost - lowest hanging fruit and all that.

I've tested these changes and they work fine across Chrome, Firefox and Safari.

I'll try out the web vault today to see if this also improves performance there, or whether it has different causes. I'll do some testing with ivy as well.

**Comment by eliykat** [comment]
@vincentsalucci I'm revisiting this PR at the moment and gave the ivy compiler a test as you suggested. Unfortunately it immediately broke the scroll even in dev, so no luck there. It must change something fairly fundamental that transcends the scrolling library.

**Comment by eliykat** [comment]
I've revisited this and I'm going to use [cdk-virtual-scroll](https://material.angular.io/cdk/scrolling/overview) instead - it's already included with Angular, better supported, and would let us use ivy in the browser. I'll close this and create a new PR once I have a working implementation using this library.

**Pull request closed without merging**
