### PR TITLE
Add new context-menu option to clear clipboard

### PR DESCRIPTION
**Pull request by PerryTrinh**
Added a small menu option when a user right clicks, enabling them to clear their clipboard manually.

NewClearClipboardOption

### CODE REVIEW

**Comment by kspearrin** [comment]
Thanks for the PR. I'm curious what is the use case for having this as a menu option? When does someone clear their clipboard in this way?

**Comment by PerryTrinh** [comment]
From personal experience, I have a habit of copying and pasting my credentials with the right click menu very often (and not using the autofill feature as much) and it would be convenient to have an option to clear the clipboard in a similar fashion. Another reason is peace of mind, I know that there is an option to clear your clipboard after a certain amount of time passes, however I often find myself clearing it manually anyways, even if I have the automatic clear option set.

**Comment by LiveChief** [comment]
Add This Please.

**Comment by eliykat** [comment]
Hi @PerryTrinh, thanks for your submission! I'm currently reviewing and cleaning up old pull requests. If you're still interested in progressing this PR, please:
* sign the Contributor License Agreement (see the link provided by the CLAassistant bot above)
* review/respond to any outstanding change requests or questions
* reply here and tag me (@) so that I can mark it for further review

As this PR is more than 12 months old, I'll close it for now. However, this is just housekeeping. We encourage our community members to get involved and make contributions, so you can comment here even after it's closed and I'll reopen it if required.

**Pull request closed without merging**
