### PR TITLE
Add Dutch translation

### PR DESCRIPTION
**Pull request by lbel**
I really like the idea of this project, and saw there wasn't a Dutch translation yet, so I decided to make one. I'm a native speaker.

### CODE REVIEW

**Comment by kspearrin** [comment]
Thanks! Will go out next release.

**Comment by kspearrin** [comment]
One small issue I found on the password generator page. The special characters string is a bit long and ends up pushing the input box down to the next line. Not sure if there is a shorter version of that string we can use or not. If not, its not a big deal.

nlissue

**Comment by kspearrin** [comment]
I also made this slight update to the copy text. Looked like a mistake or am I missing something about question marks in Dutch?

https://github.com/bitwarden/browser/commit/e5fd2545411bbe8c562f60829e3c5fe123db0260

**Comment by lbel** [comment]
About the question mark/dash you're completely right, I translated that a bit too blindly.
For the minimum special characters string we could abbreviate to just "Minimum Speciale Karakters" (and for consistency also omit "Aantal" in the string above – it means "number of" but is not really necessary here).

**Comment by kspearrin** [comment]
Sounds good.

**Comment by kspearrin** [comment]
@lbel Could you please email from the contact form on the website, https://bitwarden.com/contact/?  I'm trying to collect all of the translation contributors contact information so that I can keep you up to date via email when translations change. Thanks.

**Pull request merged**
